os: linux
env:
  - TZ=Asia/Shanghai

sudo: required

language: go

go:
  - 1.13.4

script:
  - export GO111MODULE=on 
  - make

deploy:
  provider: releases
  file:
  - bin/gaea
  - bin/gaea-cc
  overwrite: true
  skip_cleanup: true 
  api_key: $GITHUB_TOKEN
  on: 
    tags: true    #发布tag时才进行发包   
