// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package backend

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockConnectionPool is an autogenerated mock type for the MockConnectionPool type
type MockConnectionPool struct {
	mock.Mock
}

// Active provides a mock function with given fields:
func (_m *MockConnectionPool) Active() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Addr provides a mock function with given fields:
func (_m *MockConnectionPool) Addr() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Available provides a mock function with given fields:
func (_m *MockConnectionPool) Available() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Capacity provides a mock function with given fields:
func (_m *MockConnectionPool) Capacity() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *MockConnectionPool) Close() {
	_m.Called()
}

// Get provides a mock function with given fields: ctx
func (_m *MockConnectionPool) Get(ctx context.Context) (PooledConnect, error) {
	ret := _m.Called(ctx)

	var r0 PooledConnect
	if rf, ok := ret.Get(0).(func(context.Context) PooledConnect); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PooledConnect)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdleClosed provides a mock function with given fields:
func (_m *MockConnectionPool) IdleClosed() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// IdleTimeout provides a mock function with given fields:
func (_m *MockConnectionPool) IdleTimeout() time.Duration {
	ret := _m.Called()

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// InUse provides a mock function with given fields:
func (_m *MockConnectionPool) InUse() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MaxCap provides a mock function with given fields:
func (_m *MockConnectionPool) MaxCap() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Open provides a mock function with given fields:
func (_m *MockConnectionPool) Open() {
	_m.Called()
}

// Put provides a mock function with given fields: pc
func (_m *MockConnectionPool) Put(pc PooledConnect) {
	_m.Called(pc)
}

// SetCapacity provides a mock function with given fields: capacity
func (_m *MockConnectionPool) SetCapacity(capacity int) error {
	ret := _m.Called(capacity)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(capacity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetIdleTimeout provides a mock function with given fields: idleTimeout
func (_m *MockConnectionPool) SetIdleTimeout(idleTimeout time.Duration) {
	_m.Called(idleTimeout)
}

// StatsJSON provides a mock function with given fields:
func (_m *MockConnectionPool) StatsJSON() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// WaitCount provides a mock function with given fields:
func (_m *MockConnectionPool) WaitCount() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// WaitTime provides a mock function with given fields:
func (_m *MockConnectionPool) WaitTime() time.Duration {
	ret := _m.Called()

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}
