{
 "title": "gaea_proxy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "集群QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gaea_proxy_sql_timings_count_rate_total",
     "legendFormat": "total"
    },
    {
     "expr": "gaea_proxy_sql_timings_count_rate_each_namespace",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "业务流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "gaea_proxy_flow_counts_rate_namespace",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "gaea_proxy_flow_counts_rate_total",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "业务请求耗时",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "gaea_proxy_sql_timings_rate_namespace",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "SQL错误数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gaea_proxy_sql_error_counts_rate_namespace",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU 负载",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"gaea_proxy\"}[20s])) without (slave)",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(statsite.gauges.systech.gaea-proxy._.machine.*.resource.cpu.usage, 6)"
    }
   ]
  },
  {
   "title": "内存负载",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(go_memstats_alloc_bytes{job=\"gaea_proxy\"}) without (slave)",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(statsite.gauges.systech.gaea-proxy._.machine.*.resource.memory.heapAlloc, 6)"
    }
   ]
  },
  {
   "title": "流量负载",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(avg(rate(gaea_proxy_flow_counts[20s])) without (slave)) by (instance, flowdirection)",
     "legendFormat": "{{instance}}.{{flowdirection}}"
    },
    {
     "expr": "sum(sum(avg(rate(gaea_proxy_flow_counts[20s])) without (slave)) by (instance))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(avg(rate(gaea_proxy_flow_counts[20s])) without (slave)) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "会话数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(avg(gaea_proxy_session_counts) without (slave)) by (instance))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(avg(gaea_proxy_session_counts) without (slave)) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "业务会话数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(gaea_proxy_session_counts) without (slave)) by (namespace)",
     "legendFormat": "{{namespace}}",
     "target": "aliasByNode(statsite.gauges.systech.gaea-proxy.app.*.session, 5)"
    },
    {
     "expr": "sum(sum(avg(gaea_proxy_session_counts) without (slave)) by (namespace))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "协程数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(go_goroutines{job=\"gaea_proxy\"}) by (instance)",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(statsite.gauges.systech.gaea-proxy._.machine.*.resource.numOfGoroutine, 6)"
    }
   ]
  },
  {
   "title": "GC 停顿时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(go_gc_duration_seconds_sum{job=\"gaea_proxy\"}[20s]))by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "堆对象数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(go_memstats_heap_objects{job=\"gaea_proxy\"}) by (instance)",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(statsite.gauges.systech.gaea-proxy._.machine.*.resource.memory.heapObjects, 6)"
    }
   ]
  }
 ]
}