#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Auto Comment

on:
  issues:
    types: [opened]  # 触发条件：当问题被创建时
  pull_request:
    types: [opened]  # 触发条件：当拉取请求被创建时

permissions:
  issues: write  # 允许写入问题
  pull-requests: write  # 允许写入拉取请求

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issue
        uses: actions/github-script@v4
        with:
          script: |
            const issueOpened = "Thank you for raising an issue. We will try and get back to you as soon as possible. Please make sure you have given us as much context as possible.";
            const pullRequestOpened = "Thank you for raising your pull request. Please make sure you have followed our contributing guidelines. We will review it as soon as possible.";

            if (context.payload.action === 'opened') {
              const issueComment = context.payload.issue ? issueOpened : pullRequestOpened;
              await github.issues.createComment({
                ...context.repo,
                issue_number: context.payload.issue ? context.payload.issue.number : context.payload.pull_request.number,
                body: issueComment
              });
            }
